!Config
store_engine: memory
store_url: memory://
user_agent: wvprs
host: 0.0.0.0
my_ip: ""
sip_port: 5060
http_port: 6070
sip_domain: 6101130049
sip_id: 61011300490000000001
sip_password: aseqw_+hiy123
sip_algorithm: md5
sip_nonce: ad50a5ec1a5587f18210bbdf76d7bd84
sip_realm: 6101130049
socket_recv_buffer_size: 65535
stream_timeout_seconds: 180
device_timeout_seconds: 300